### ISSUE TITLE
Compilation fails: unknown type name 'tdlsConnInfo_t'

### ISSUE THREAD

**Issue by Riccorbypro** [sonyxperiadev/prima#3]
Every time I try to compile the kernel with this module, I get

```
    prima/CORE/HDD/inc/wlan_hdd_tdls.h:480:1: error: unknown type name 'tdlsConnInfo_t'
```

I have checked the code, everything seems to be in order. I'm also following the copyleft instructions over at the Dev World. Please assist.

**Comment by Riccorbypro** [comment]
Issue fixed.

**Comment by CaptainThrowback** [comment]
How did you fix this?

**Comment by Riccorbypro** [comment]
In one of the files in the `prima/CORE/HDD/` folder, there's a file that contains the configuration for the entire WLAN HDD module. In that file, the `tdlsConnInfo_t` is at the end, instead of alongside the `tdlsConnInfo_s` (I think, I'm out at the moment, so I can't look) type. Just move the definition of `tdlsConnInfo_*` to the top of the section for tdls.

I suppose if the issue still persists for some, the issue should still be open.

**Comment by khanfrd** [comment]
it it because QCOM_TDLS entry is missing from [Kconfig](https://github.com/sonyxperiadev/prima/blob/master/Kconfig),

**Comment by Aesthermortis** [comment]
I have the same problem, I have not been able to solve it :/

**Comment by jerpelea** [comment]
this code has been updated and included in the kernel

**Comment by shashi918** [comment]
i cant solve this issue please help

**Comment by hhihhio** [comment]
config PRIMA_WLAN_11AC_HIGH_TP
	bool "Enable the Prima WLAN 802.11ac High Throughput option (depends upon kernel support)"
	default n

config QCOM_TDLS
	bool "Enable TDLS feature"
	default n

config WLAN_FEATURE_11W
	bool "Enable the WLAN 802.11w Protected Management Frames feature"
	default n
